import { defineQuestionnaireInstrument } from './questionnaire.js';

/**
 * Editable questionnaire content for the one-trial demo.
 * Change wording, options and block composition here; rendering and storage
 * are implemented elsewhere. These are pilot items, not a validated scale.
 */
export const QUESTIONNAIRE_INSTRUMENT = defineQuestionnaireInstrument({
  version: 'demo-questionnaire-0.1.0',
  wordingProfile: 'SELF_AI',
  title: '预测任务问卷',
  blocks: [
    {
      id: 'pre-prior-beliefs',
      position: 'pre',
      eyebrow: '开始前 · 1 / 2',
      title: '开始前的判断',
      intro: '请根据当前直觉作答。这里没有标准答案。',
      submitLabel: '继续理解检验',
      randomizeQuestions: true,
      questions: [
        {
          id: 'PRE_PRIOR_ACC_SELF',
          kind: 'slider',
          prompt: '在尚未看到正式题结果前，您预计自己在本实验正式题中的正确率是多少？',
          required: true,
          min: 0,
          max: 100,
          step: 1,
          minLabel: '0% 完全不会答对',
          maxLabel: '100% 全部答对',
          valueSuffix: '%',
        },
        {
          id: 'PRE_PRIOR_ACC_AI',
          kind: 'slider',
          prompt: '在尚未看到正式题结果前，您预计本实验中 AI 助手建议的正确率是多少？',
          required: true,
          min: 0,
          max: 100,
          step: 1,
          minLabel: '0% 完全不会答对',
          maxLabel: '100% 全部答对',
          valueSuffix: '%',
        },
      ],
    },
    {
      id: 'pre-comprehension',
      position: 'pre',
      eyebrow: '开始前 · 2 / 2',
      title: '确认您已理解任务',
      intro: '如有答错，页面会提示您重新检查相应规则。',
      submitLabel: '通过检验并开始',
      questions: [
        {
          id: 'COMP_TARGET',
          kind: 'single_choice',
          prompt: '每轮需要预测的是哪一项？',
          required: true,
          correctAnswer: 'next_winner',
          incorrectFeedback: '请注意：目标是下一轮实际中奖的机器，不是历史命中率最高的机器。',
          options: [
            { value: 'next_winner', label: '下一轮实际中奖的机器' },
            { value: 'historical_best', label: '历史命中率最高的机器' },
            { value: 'favorite', label: '自己最喜欢的机器' },
          ],
        },
        {
          id: 'COMP_INITIAL_LOCK',
          kind: 'single_choice',
          prompt: '提交独立预测后，在查看建议前还能修改吗？',
          required: true,
          correctAnswer: 'cannot_change',
          incorrectFeedback: '独立预测提交后会锁定。',
          options: [
            { value: 'can_change', label: '可以随时修改' },
            { value: 'cannot_change', label: '不能修改' },
          ],
        },
        {
          id: 'COMP_ADVICE_FALLIBLE',
          kind: 'single_choice',
          prompt: 'AI 助手的建议是否保证正确？',
          required: true,
          correctAnswer: 'not_guaranteed',
          incorrectFeedback: 'AI 建议可能正确，也可能错误。',
          options: [
            { value: 'guaranteed', label: '保证正确' },
            { value: 'not_guaranteed', label: '不保证正确' },
          ],
        },
        {
          id: 'COMP_FINAL_CHOICE',
          kind: 'single_choice',
          prompt: '查看建议后，最终预测是否必须跟随建议？',
          required: true,
          correctAnswer: 'free_choice',
          incorrectFeedback: '您可以保留原判断，也可以改变最终预测。',
          options: [
            { value: 'must_follow', label: '必须跟随建议' },
            { value: 'free_choice', label: '可以保留或改变自己的预测' },
          ],
        },
      ],
    },
    {
      id: 'post-performance-beliefs',
      position: 'post',
      eyebrow: '任务后问卷 · 1 / 4',
      title: '您如何理解刚才的任务？',
      intro: '请根据刚才的实际体验作答。',
      submitLabel: '继续',
      questions: [
        {
          id: 'POST_MC_DISCLOSURE',
          kind: 'single_choice',
          prompt: '正式任务开始前，页面是否明确展示过 AI 助手的总体正确率？',
          required: true,
          options: [
            { value: 'yes', label: '是' },
            { value: 'no', label: '否' },
            { value: 'unsure', label: '不确定' },
          ],
        },
        {
          id: 'POST_MC_SOURCE',
          kind: 'single_choice',
          prompt: '刚才页面中的建议被说明为什么来源？',
          required: true,
          options: [
            { value: 'ai', label: 'AI 助手' },
            { value: 'human', label: '人类预测者' },
            { value: 'unknown', label: '没有说明或不记得' },
          ],
        },
        {
          id: 'POST_PERCEIVED_ACC_SELF',
          kind: 'slider',
          prompt: '综合刚才的任务，您认为自己的独立预测正确率约为多少？',
          required: true,
          min: 0,
          max: 100,
          step: 1,
          minLabel: '0%',
          maxLabel: '100%',
          valueSuffix: '%',
        },
        {
          id: 'POST_PERCEIVED_ACC_AI',
          kind: 'slider',
          prompt: '综合刚才的任务，您认为 AI 助手建议的正确率约为多少？',
          required: true,
          min: 0,
          max: 100,
          step: 1,
          minLabel: '0%',
          maxLabel: '100%',
          valueSuffix: '%',
        },
      ],
    },
    {
      id: 'post-trust',
      position: 'post',
      eyebrow: '任务后问卷 · 2 / 4',
      title: '对两种判断来源的评价',
      intro: '1 表示非常不同意，7 表示非常同意。题目中的“AI 助手”指刚才任务中提供建议的助手。',
      submitLabel: '继续',
      randomizeQuestions: true,
      questions: [
        ...[
          ['POST_PT_SELF_RELIABLE', '在这个预测任务中，我认为自己的独立判断是可靠的。'],
          ['POST_PT_SELF_COMPETENT', '我认为自己有能力完成这个预测任务。'],
          ['POST_PT_SELF_DEPENDABLE', '完成同类预测时，我认为自己的判断表现值得信赖。'],
          ['POST_AT_SELF_RELY', '如果继续完成同类任务，我愿意依赖自己的判断。'],
          ['POST_AT_SELF_BASIS', '结果不确定时，我愿意把自己的判断作为最终决定的重要依据。'],
          ['POST_PT_AI_RELIABLE', '在这个预测任务中，我认为 AI 助手的判断是可靠的。'],
          ['POST_PT_AI_COMPETENT', '我认为 AI 助手有能力完成这个预测任务。'],
          ['POST_PT_AI_DEPENDABLE', '完成同类预测时，我认为 AI 助手的表现值得信赖。'],
          ['POST_AT_AI_RELY', '如果继续完成同类任务，我愿意依赖 AI 助手的判断。'],
          ['POST_AT_AI_BASIS', '结果不确定时，我愿意把 AI 助手的判断作为最终决定的重要依据。'],
        ].map(([id, prompt]) => ({
          id: id ?? '',
          kind: 'likert' as const,
          prompt: prompt ?? '',
          required: true,
          min: 1,
          max: 7,
          step: 1,
          minLabel: '非常不同意',
          maxLabel: '非常同意',
        })),
      ],
    },
    {
      id: 'post-threshold-process',
      position: 'post',
      eyebrow: '任务后问卷 · 3 / 4',
      title: '判断标准与决策过程',
      intro: '最低正确率题用于了解您的判断标准，不存在标准答案。',
      submitLabel: '继续',
      questions: [
        {
          id: 'POST_MIN_ACC_SELF',
          kind: 'slider',
          prompt:
            '继续完成相同任务时，您至少需要确认自己的长期正确率达到多少，才愿意主要依据自己的判断？',
          required: true,
          min: 0,
          max: 100,
          step: 1,
          minLabel: '0%',
          maxLabel: '100%',
          valueSuffix: '%',
        },
        {
          id: 'POST_MIN_ACC_AI',
          kind: 'slider',
          prompt:
            '继续完成相同任务时，您至少需要确认 AI 助手的长期正确率达到多少，才愿意将其作为主要判断依据？',
          required: true,
          min: 0,
          max: 100,
          step: 1,
          minLabel: '0%',
          maxLabel: '100%',
          valueSuffix: '%',
        },
        ...[
          ['POST_PROCESS_INITIAL', '我自己的初始判断影响了最终预测。'],
          ['POST_PROCESS_ADVICE', '助手给出的具体建议影响了最终预测。'],
          ['POST_PROCESS_PERFORMANCE', '页面显示或我观察到的正确率信息影响了最终预测。'],
          ['POST_PROCESS_PAYOFF', '答对或答错对应的积分后果影响了最终预测。'],
        ].map(([id, prompt]) => ({
          id: id ?? '',
          kind: 'likert' as const,
          prompt: prompt ?? '',
          required: true,
          min: 1,
          max: 7,
          step: 1,
          minLabel: '完全没有影响',
          maxLabel: '影响非常大',
        })),
      ],
    },
    {
      id: 'post-experience',
      position: 'post',
      eyebrow: '任务后问卷 · 4 / 4',
      title: '最后几个问题',
      submitLabel: '提交问卷并完成实验',
      questions: [
        ...[
          ['POST_EXP_CLEAR', '实验说明清楚易懂。'],
          ['POST_EXP_REALISM', '实验中的预测与助手交互让我感到真实。'],
          ['POST_EXP_EFFORT', '我认真完成了每一步预测。'],
          ['POST_EXP_TECH', '实验过程中出现了影响作答的技术问题。'],
          ['POST_AI_TASK_FAM', '我熟悉 AI 辅助预测或决策工具。'],
          ['POST_SLOT_FAM', '在本实验前，我熟悉老虎机或概率预测任务。'],
        ].map(([id, prompt]) => ({
          id: id ?? '',
          kind: 'likert' as const,
          prompt: prompt ?? '',
          required: true,
          min: 1,
          max: 7,
          step: 1,
          minLabel: '非常不同意',
          maxLabel: '非常同意',
        })),
        {
          id: 'POST_AI_USE_FREQ',
          kind: 'single_choice',
          prompt: '过去三个月，您使用生成式 AI 工具的频率是？',
          required: true,
          options: [
            { value: 'never', label: '从未使用' },
            { value: 'less_than_monthly', label: '少于每月一次' },
            { value: 'monthly', label: '每月数次' },
            { value: 'weekly', label: '每周数次' },
            { value: 'daily', label: '几乎每天' },
          ],
        },
        {
          id: 'POST_SUSP_PURPOSE',
          kind: 'text',
          prompt: '您认为这项研究主要想了解什么？',
          required: true,
          multiline: true,
          maxLength: 500,
          placeholder: '请用一两句话说明',
        },
        {
          id: 'POST_EXP_TECH_TEXT',
          kind: 'text',
          prompt: '如有影响作答的技术问题，请简要说明。',
          help: '没有问题可以留空。',
          required: false,
          multiline: true,
          maxLength: 500,
          placeholder: '选填',
        },
      ],
    },
  ],
});
